### ISSUE TITLE
Threadpool error: Exception ignored on calling ctypes callback function

### ISSUE THREAD

**Issue by skjerns** [mne-tools/mne-bids-pipeline#1026]
I inconsistently get the following error that does **not** cause the pipeline to crash ,so I ignored it for now. 
However, I am not sure if it affects the underlying computations.

```
│17:07:29│ ⏳️ sub-04 Adding config and sys info to report
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x7fd47d95f240>
Traceback (most recent call last):
  File "/zi/home/user/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/zi/home/user/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zi/home/user/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/zi/home/user/anaconda3/lib/python3.11/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by larsoner** [comment]
Can you try updating `threadpoolctl` to see if it helps? That line does not exist in 3.5.0

**Comment by skjerns** [comment]
uhh yes, I had `threadpoolctl==2.2.0` installed, upgrading to `threadpool==3.5.0` solved the problem (that was probably only cosmetic anyway, did not see any problems) :)
