### ISSUE TITLE
CI runs fail for ERP CORE

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#278]
CI runs have been failing for ERP CORE a couple of times now. At first I thought it's just a fluke; but it's not. I am quite confident it is **not** a bug in the Pipeline per se, but an issue with PyVista or the way we run the tests involving PyVista. Example traceback:

```python
Traceback (most recent call last):
  File "/home/circleci/miniforge/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/circleci/miniforge/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/circleci/project/scripts/report/01-make_reports.py", line 241, in run_report
    if mne.viz.get_3d_backend() is not None:
  File "/home/circleci/miniforge/lib/python3.8/site-packages/mne/viz/backends/renderer.py", line 132, in get_3d_backend
    backend = _get_3d_backend()
  File "/home/circleci/miniforge/lib/python3.8/site-packages/mne/viz/backends/renderer.py", line 146, in _get_3d_backend
    _reload_backend(name)
  File "/home/circleci/miniforge/lib/python3.8/site-packages/mne/viz/backends/renderer.py", line 34, in _reload_backend
    backend = importlib.import_module(name=_backend_name_map[backend_name],
  File "/home/circleci/miniforge/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/circleci/miniforge/lib/python3.8/site-packages/mne/viz/backends/_qt.py", line 11, in <module>
    import pyvista
  File "/home/circleci/miniforge/lib/python3.8/site-packages/pyvista/__init__.py", line 62, in <module>
    os.makedirs(USER_DATA_PATH)
  File "/home/circleci/miniforge/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/circleci/.local/share/pyvista'
```
[Failed workflow](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/1531/workflows/c7f466b2-8717-4aba-ac5c-9e42f3452e8c/jobs/2865)

This only occurs for our ERP CORE tests, where we process multiple participants in parallel. If I'm not mistaken, in no other test do we do that. So it seems like some sort of race condition when rendering 3D models for multiple reports in parallel.

@larsoner @GuillaumeFavelier Any idea if we could somehow work around this? Is this maybe a fundamental issue we're hitting here, trying to use PyVista from multiple processes in parallel?

In either case, I think PyVista should handle the situation more gracefully :)

**Comment by larsoner** [comment]
>  So it seems like some sort of race condition when rendering 3D models for multiple reports in parallel.

Yes it seems related to two Python instances trying to create a directory at the same time. The PyVista code could be updated to have `exist_ok=True` in the `makedirs` call (feel free to make a PR for this) but in the meantime I would just do a `mkdir -p /home/circleci/.local/share/pyvista` in CircleCI somewhere before running the command to work around the issue

**Comment by hoechenberger** [comment]
Thanks @larsoner, this fixed it indeed. I was hesitant to try this extremely simple approach at first because I thought that maybe it's about a locking mechanism to ensure PyVista functionality, but this seems not to be the case. So yeah, small bug in PyVista, I'd say :)
