### ISSUE TITLE
One CI run fails due to download error

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#338]
```
👋 Hello! This is openneuro-py 2021.5. Great to see you! 🤗

   👉 Please report problems 🤯 and bugs 🪲 at
      https://github.com/hoechenberger/openneuro-py/issues

🌍 Preparing to download ds003392 …
👉 Retrieving up to 19 files (5 concurrent downloads).
Traceback (most recent call last):                                                                                
  File "/home/circleci/project/tests/download_test_data.py", line 152, in <module>
    main(dataset)
  File "/home/circleci/project/tests/download_test_data.py", line 141, in main
    _download(ds_name=ds_name, ds_path=ds_path)
  File "/home/circleci/project/tests/download_test_data.py", line 122, in _download
    download_func(ds_name=ds_name, ds_path=ds_path)
  File "/home/circleci/project/tests/download_test_data.py", line 34, in _download_via_openneuro
    openneuro.download(dataset=DATASET_OPTIONS[ds_name]['openneuro'],
  File "/home/circleci/.local/lib/python3.8/site-packages/openneuro/download.py", line 586, in download
    asyncio.run(_download_files(**kwargs))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/circleci/.local/lib/python3.8/site-packages/openneuro/download.py", line 455, in _download_files
    await asyncio.gather(*download_tasks)
  File "/home/circleci/.local/lib/python3.8/site-packages/openneuro/download.py", line 322, in _download_file
    await _retrieve_and_write_to_disk(
  File "/home/circleci/.local/lib/python3.8/site-packages/openneuro/download.py", line 420, in _retrieve_and_write_to_disk
    raise RuntimeError(
RuntimeError: Server claimed size of /home/circleci/mne_data/ds003392/dataset_description.jsonwould be 1029 bytes, but downloaded 2022 byes.
```

Probably something I'll need to address in `openneuro-py`.

**Comment by hoechenberger** [comment]
This has meanwhile been resolved upstream in `openneuro-py`.
