### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#484]
Hi @hoechenberger 

Sorry for bothering you that early:

I get this error:
```

**python run.py --config=/Users/guiomar/Documents/config_ds000247_guio.py**

[15:30:44] mne-bids-pipeline/config Using custom configuration: /Users/guiomar/Documents/config_ds000247_guio.py
Traceback (most recent call last):
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/run.py", line 246, in <module>
    fire.Fire(process)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/run.py", line 196, in process
    SCRIPT_MODULES = _get_script_modules(
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/run.py", line 71, in _get_script_modules
    from scripts import init
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/init/__init__.py", line 1, in <module>
    from . import _00_init_derivatives_dir
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/init/_00_init_derivatives_dir.py", line 18, in <module>
    import config
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/config.py", line 1962, in <module>
    _all_datatypes = mne_bids.get_datatypes(root=get_bids_root())
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/config.py", line 1942, in get_bids_root
    return (pathlib.Path(bids_root)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/pathlib.py", line 373, in resolve
    return _resolve(base, str(path)) or sep
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/pathlib.py", line 357, in _resolve
    target = accessor.readlink(newpath)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/pathlib.py", line 462, in readlink
    return os.readlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/guiomar/Users'
```

It's very weird because I have this in my config file:

```
bids_root = '/Users/guiomar/ds000247' 
deriv_root = '/Users/guiomar/mne-bids-pipeline/ds000247'
```

So I don't know why it's looking for '/Users/guiomar/**Users**'

**Comment by guiomar** [comment]
Not sure what happened, it's working fine now
