### ISSUE TITLE
sources with already computed freesurfer files

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#515]
Hi @hoechenberger!

I copy here the question I wrote you on discord and email back in January, so maybe it easier to keep track here. Sorry for reaching out maybe not on the most adecuate channels, there are so many parallel tools for communication that it can be a bit overwhelming.

I'm retaking what we talked about including source psd on the mne-bids-pipeline. I tried to set the config file for ds000247 (omega dataset). However, I find I should have freesurfer installed otherwise it gives me error on scripts.source._01_make_bem_surfaces (saying: The FREESURFER_HOME environment variable is not set).
Since I already have the freesurfer files on the derivatives folder (provided with the ds000247 dataset). I wonder if I should still need to compute the freesurfer in the pipeline myself? Or maybe this is happening because mne-bids-pipeline requires some additional files that are not present in the provided derivatives folder?

Thanks a lot!

**Comment by hoechenberger** [comment]
Hey! oh noes, I'm so super bad with Discord and apparently with emails too, I'm so sorry! Now that I read this message, I remember your email – I forgot to add it to my todo stack!

Which config file are you using, the one from our examples?

**Comment by guiomar** [comment]
You are super fast at replying! (I'm very much appreciated), I just need to learn the more adecuate communication channels :) Happy you are good and back again!

Yes, I'm using the version of the example with slightly addapted to my paths. And the data from OpenNeuro ds00247 (raw and derivatives). Just for sub-0002.

I copy here my config.py file, I tried different attempts for `subjects_dir`:

```
study_name = 'ds000247'
bids_root = '/Users/guiomar/ds000247'
deriv_root = '/Users/guiomar/mne-bids-pipeline/ds000247'
#subjects_dir = f'{bids_root}/derivatives/freesurfer/subjects'
#subjects_dir = '/Users/guiomar/ds000247/derivatives/freesurfer'
#subjects_dir = '/Users/guiomar/ds000247/derivatives/freesurfer/'
subjects_dir = '/Users/guiomar/ds000247'
subjects_dir = '/Users/guiomar/ds000247/derivatives'

subjects = ['0002']
sessions = ['01']
task = 'rest'

crop_runs = (0, 100)  # to speed up computations

ch_types = ['meg']
spatial_filter = 'ssp'

l_freq = 1.0
h_freq = 40.0

rest_epochs_duration = 10
rest_epochs_overlap = 0

epochs_tmin = 0
baseline = None
```


And this is the error I get:

```
[16:57:18] source/_01_make_bem_surfaces A critical error occurred.
Traceback (most recent call last):
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/run.py", line 246, in <module>
    fire.Fire(process)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/run.py", line 241, in process
    script_module.main()
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/source/_01_make_bem_surfaces.py", line 142, in main
    logs = parallel(
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/source/_01_make_bem_surfaces.py", line 143, in <genexpr>
    run_func(cfg=get_config(subject=subject), subject=subject)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/config.py", line 2290, in wrapper
    raise(e)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/config.py", line 2279, in wrapper
    out = func(*args, **kwargs)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/source/_01_make_bem_surfaces.py", line 124, in make_bem_and_scalp_surface
    make_bem(cfg=cfg, subject=subject)
  File "/Users/guiomar/Documents/GitHub/mne-bids-pipeline/scripts/source/_01_make_bem_surfaces.py", line 65, in make_bem
    bem_func(
  File "<decorator-gen-64>", line 22, in make_watershed_bem
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/mne/bem.py", line 1078, in make_watershed_bem
    env, mri_dir, bem_dir = _prepare_env(subject, subjects_dir)
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/mne/bem.py", line 1665, in _prepare_env
    fs_home = _check_freesurfer_home()
  File "/Users/guiomar/opt/anaconda3/envs/mne_env/lib/python3.9/site-packages/mne/utils/check.py", line 783, in _check_freesurfer_home
    raise RuntimeError(
RuntimeError: The FREESURFER_HOME environment variable is not set.
```

**Comment by guiomar** [comment]
Thnaks Richard! I don't have FS on my personal computer, but I'll have a look to install it if necessary (also happy to try your alternative if this doen't mean extra work for you).

Is there any other source reconstruction option that doesn't require bem folder? I thought we were providing the main FS files required for source reconstruction in the data, but if this is not the case, we may need to update the dataset to facilitate people these steps. Thanks!

**Comment by hoechenberger** [comment]
@larsoner @agramfort
WDYT about making the `minimal_cmds` (which we use on our CI systems to avoid having to install a full-fledged FreeSurfer) available to "common" users? There could be an MNE function that retrieves and unpacks the binaries automatically.

**Comment by agramfort** [comment]
I don't know if we can legally do this....

**Comment by larsoner** [comment]
This seems more or less solved, but feel free to reopen if we should update some doc somewhere
