### ISSUE TITLE
Internal assertion for outfiles triggered by splits

### ISSUE THREAD

**Issue by adswa** [mne-tools/mne-bids-pipeline#593]
I just found this repo and wanted to try it out because it looks super cool! When I ran today's version of the pipeline (commit 143654a346945e2422b8a1fcd9976bfb734a19d6) on some data of mine, this [recently](https://github.com/mne-tools/mne-bids-pipeline/commit/8c66b69af9a63a9389f65e2012d63e55d14e28fd) added internal check https://github.com/mne-tools/mne-bids-pipeline/blob/143654a346945e2422b8a1fcd9976bfb734a19d6/config.py#L2928-L2943
seems to not account for splits in the outfiles and fails. 

In my particular case, I'm seeing 
```
(magma) adina@cpu11 in /data/project/magma/mne-bids-pipeline-main
❱ python run.py --config ../magma-bids/config.py           
[17:51:10] mne-bids-pipeline-main/config Using custom configuration: ../magma-bids/config.py
[2022-08-24 17:51:11] 👋 Welcome aboard the MNE BIDS Pipeline!

[2022-08-24 17:51:11] 🚀 Now running script: scripts.init._00_init_derivatives_dir 👇
[17:51:11] init/_00_init_derivatives_dir Initializing output directories.
[2022-08-24 17:51:11] 🎉 Done running script: scripts.init._00_init_derivatives_dir 👆
[2022-08-24 17:51:11] 🚀 Now running script: scripts.preprocessing._01_maxfilter 👇
[17:51:11] init/_00_init_derivatives_dir Skipping …
[2022-08-24 17:51:11] 🎉 Done running script: scripts.preprocessing._01_maxfilter 👆
[2022-08-24 17:51:11] 🚀 Now running script: scripts.preprocessing._02_frequency_filter 👇
[17:51:24] preprocessing/_02_frequency_filter sub-01 Finding breaks has been disabled by the user.
[17:51:24] preprocessing/_02_frequency_filter sub-01 Band-pass filtering experimental data; range: 0.3 – 40.0 Hz
[17:51:56] preprocessing/_02_frequency_filter sub-01 A critical error occured. The error message was: Missing at least one output file: 
- raw_filt=/data/project/magma/magma-bids/derivatives/mne-bids-pipeline/sub-01/meg/sub-01_task-magma_proc-filt_raw.fif
This should not happen unless some files have been manually moved or deleted. You need to flush your cache to fix this.

Aborting pipeline run. The full traceback is:

Traceback (most recent call last):

  File "/data/project/magma/mne-bids-pipeline-main/config.py", line 2826, in wrapper
    out = memory.cache(func)(*args, **kwargs)

  File "/data/project/magma/mne-bids-pipeline-main/config.py", line 2941, in wrapper
    'This should not happen unless some files '

ValueError: Missing at least one output file: 
- raw_filt=/data/project/magma/magma-bids/derivatives/mne-bids-pipeline/sub-01/meg/sub-01_task-magma_proc-filt_raw.fif
This should not happen unless some files have been manually moved or deleted. You need to flush your cache to fix this.
```

as the outfile was split into two parts and did not correspond to the desired ``sub-01_task-magma_proc-filt_raw.fif`` file name anymore.

```
(magma) adina@cpu11 in /data/project/magma/mne-bids-pipeline-main
❱ ls ../magma-bids/derivatives/mne-bids-pipeline/sub-01/meg
sub-01_task-magma_proc-filt_split-01_raw.fif  sub-01_task-magma_proc-filt_split-02_raw.fif

```

**Comment by hoechenberger** [comment]
Thanks for reporting this, @adswa!

@larsoner @agramfort Could you take a look please? 🙏

**Comment by hoechenberger** [comment]
@larsoner How about introducing an undocumented non-public config option (a constant with a name starting with `_`) for this exact purpose?

**Comment by larsoner** [comment]
Perfect, I was hoping there would be some mechanism like that!

**Comment by agramfort** [comment]
sound like a good idea !
