### ISSUE TITLE
BUG: Broken testing dataset

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#599]
Locally I get:
```
$ python tests/download_test_data.py -d ds001971

----------------------

👋 Hello! This is openneuro-py 2022.1.0. Great to see you! 🤗

   👉 Please report problems 🤯 and bugs 🪲 at
      https://github.com/hoechenberger/openneuro-py/issues

🌍 Preparing to download ds001971 …
Traceback (most recent call last):
  File "/Users/larsoner/python/mne-bids-pipeline/tests/download_test_data.py", line 155, in <module>
    main(dataset)
  File "/Users/larsoner/python/mne-bids-pipeline/tests/download_test_data.py", line 144, in main
    _download(ds_name=ds_name, ds_path=ds_path)
  File "/Users/larsoner/python/mne-bids-pipeline/tests/download_test_data.py", line 125, in _download
    download_func(ds_name=ds_name, ds_path=ds_path)
  File "/Users/larsoner/python/mne-bids-pipeline/tests/download_test_data.py", line 34, in _download_via_openneuro
    openneuro.download(
  File "/Users/larsoner/opt/miniconda3/envs/mne/lib/python3.10/site-packages/openneuro/download.py", line 656, in download
    raise RuntimeError(f'Could not find path '
RuntimeError: Could not find path sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-01_events.tsvsub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-01_eeg.set in the dataset. Please check your includes.
```
@hoechenberger how do you debug and fix these things?

**Comment by larsoner** [comment]
Closing for https://github.com/mne-tools/mne-bids/issues/1065
