### ISSUE TITLE
on_error='debug' is somehow behaving incorrectly / is broken

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#654]
I edited `config_ERP_CORE.py` to contain the following settings:

```python
on_error = 'debug'
# parallel_backend = 'dask'
```

Then I edited `_02_frequency_filter.py` to raise an exception:
```python
@failsafe_run(script_path=__file__,
              get_input_fnames=get_input_fnames_frequency_filter)
def filter_data(
    *,
    cfg,
    subject: str,
    session: Optional[str],
    run: str,
    in_files: dict,
) -> None:
    """Filter data from a single subject."""
    raise ValueError('Foo')
```

Now I run the pipeline:
```
❯ MNE_BIDS_STUDY_TASK=MMN mne_bids_pipeline --config mne_bids_pipeline/tests/configs/config_ERP_CORE.py
[2022-11-10 11:38:33] ╶╴👋 Welcome aboard the MNE BIDS Pipeline!
[2022-11-10 11:38:33] ╶╴🧾 Using configuration: mne_bids_pipeline/tests/configs/config_ERP_CORE.py
[2022-11-10 11:38:33] ┌╴🚀 scripts/init/_00_init_derivatives_dir Now running  👇
[2022-11-10 11:38:35] └╴🎉 scripts/init/_00_init_derivatives_dir Done running 👆 [2s]
[2022-11-10 11:38:35] ┌╴🚀 scripts/init/_01_find_empty_room Now running  👇
[2022-11-10 11:38:35] │ ⏩ mne_bids_pipeline/_config_import Skipping, empty-room data only relevant for MEG …
[2022-11-10 11:38:35] └╴🎉 scripts/init/_01_find_empty_room Done running 👆 [1s]
[2022-11-10 11:38:35] ┌╴🚀 scripts/preprocessing/_01_maxfilter Now running  👇
[2022-11-10 11:38:35] │ ⏩ preprocessing/_01_maxfilter Skipping …
[2022-11-10 11:38:35] └╴🎉 scripts/preprocessing/_01_maxfilter Done running 👆 [1s]
[2022-11-10 11:38:35] ┌╴🚀 scripts/preprocessing/_02_frequency_filter Now running  👇
[2022-11-10 11:38:35] │ ⏳️ preprocessing/_02_frequency_filter A critical error occurred. The error message was: Foo

Starting post-mortem debugger.
Traceback (most recent call last):
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 64, in wrapper
    out = memory.cache(func)(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 253, in wrapper
    out_files = memorized_func(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 537, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 779, in call
    output = self.func(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 176, in filter_data
    raise ValueError('Foo')
ValueError: Foo
[2022-11-10 11:38:35] │ ⏳️ preprocessing/_02_frequency_filter A critical error occurred. The error message was: Foo

Starting post-mortem debugger.
Traceback (most recent call last):
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 64, in wrapper
    out = memory.cache(func)(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 253, in wrapper
    out_files = memorized_func(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 537, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 779, in call
    output = self.func(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 176, in filter_data
    raise ValueError('Foo')
ValueError: Foo
> /Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py(176)filter_data()
-> raise ValueError('Foo')
> /Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py(176)filter_data()
-> raise ValueError('Foo')
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 64, in wrapper
    out = memory.cache(func)(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 253, in wrapper
    out_files = memorized_func(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 537, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/memory.py", line 779, in call
    output = self.func(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 176, in filter_data
    raise ValueError('Foo')
ValueError: Foo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py", line 109, in wrapper
    pdb.post_mortem(tb)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/pdb.py", line 1642, in post_mortem
    p.interaction(None, t)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
RuntimeError: input(): lost sys.stdin
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hoechenberger/mambaforge/envs/mne/bin/mne_bids_pipeline", line 8, in <module>
    sys.exit(main())
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/run.py", line 171, in main
    script_module.main(config=config_imported)
  File "/Users/hoechenberger/Development/mne-bids-pipeline/mne_bids_pipeline/scripts/preprocessing/_02_frequency_filter.py", line 338, in main
    logs = parallel(
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/hoechenberger/mambaforge/envs/mne/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
RuntimeError: input(): lost sys.stdin
```
So the debugger doesn't start… or actually, it seems to start but then loses its input terminal (?)

I believe this used to work?

**Comment by larsoner** [comment]
Yes it should work, I can open a PR to fix it. It's actually possible it didn't work with `dask` (?), but in any case I think the fix is to make sure the backend is forced to be `loky` and `n_jobs=1` (effectively) when debug mode is on.
