### ISSUE TITLE
Sensor group level analysis & report steps not cached?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#722]
My pipeline run crashed on the source level as I didn't have the FS files:

```
[13:07:45] │ ⏳️ sensor/_99_group_average sub-average Saving report: /Users/richardhochenberger/mne_data/derivatives/mne-bids-pipeline/ds000248_no_mri/sub-average/meg/sub-average_task-audiovisual_report.html
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:07:45] └╴🎉 sensor/_99_group_average Done running  👆 [45s]
[13:07:45] ┌╴🚀 source/_01_make_bem_surfaces Now running  👇
[13:07:45] │ ⏩ source/_01_make_bem_surfaces Skipping, BEM surface extraction not needed for MRI template …
Traceback (most recent call last):
  File "/Users/richardhochenberger/mambaforge/envs/mne/bin/mne_bids_pipeline", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_main.py", line 211, in main
    step_module.main(config=config_imported)
  File "/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/steps/source/_01_make_bem_surfaces.py", line 131, in main
    mne.datasets.fetch_fsaverage(get_fs_subjects_dir(config))
  File "<decorator-gen-588>", line 12, in fetch_fsaverage
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/mne/datasets/_fsaverage/base.py", line 67, in fetch_fsaverage
    subjects_dir = _set_montage_coreg_path(subjects_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/mne/datasets/_fsaverage/base.py", line 127, in _set_montage_coreg_path
    subjects_dir = _get_create_subjects_dir(subjects_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/mne/datasets/_fsaverage/base.py", line 87, in _get_create_subjects_dir
    subjects_dir = get_subjects_dir(subjects_dir, raise_error=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/mne/utils/config.py", line 381, in get_subjects_dir
    subjects_dir = _check_fname(
                   ^^^^^^^^^^^^^
  File "<decorator-gen-0>", line 12, in _check_fname
  File "/Users/richardhochenberger/mambaforge/envs/mne/lib/python3.11/site-packages/mne/utils/check.py", line 245, in _check_fname
    raise FileNotFoundError(f'{name} does not exist: {fname}')
FileNotFoundError: subjects_dir does not exist: /Users/richardhochenberger/mne_data/ds000248/derivatives/freesurfer/subjects
```

I added the files and re-ran the pipeline, but instead of starting directly with the source level processing, it re-created the sensor-level group average reports first:

```
❯ mne_bids_pipeline ./mne_bids_pipeline/tests/configs/config_ds000248_no_mri.py
[13:19:27] ╶╴👋 Welcome aboard the MNE BIDS Pipeline!
[13:19:27] ╶╴🧾 Using configuration: ./mne_bids_pipeline/tests/configs/config_ds000248_no_mri.py
[13:19:27] ┌╴🚀 init/_01_init_derivatives_dir Now running  👇
[13:19:27] └╴🎉 init/_01_init_derivatives_dir Done running  👆 [1s]
[13:19:27] ┌╴🚀 init/_02_find_empty_room Now running  👇
[13:19:27] │ ⏩ init/_02_find_empty_room Skipping, process_empty_room is set to False …
[13:19:27] └╴🎉 init/_02_find_empty_room Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_01_data_quality Now running  👇
[13:19:27] │ ✅ preprocessing/_01_data_quality sub-01 run-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 preprocessing/_01_data_quality Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_02_maxfilter Now running  👇
[13:19:27] │ ⏩ preprocessing/_02_maxfilter Skipping …
[13:19:27] └╴🎉 preprocessing/_02_maxfilter Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_03_frequency_filter Now running  👇
[13:19:27] │ ✅ preprocessing/_03_frequency_filter sub-01 run-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 preprocessing/_03_frequency_filter Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_04_make_epochs Now running  👇
[13:19:27] │ ✅ preprocessing/_04_make_epochs sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 preprocessing/_04_make_epochs Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_05a_run_ica Now running  👇
[13:19:27] │ ⏩ preprocessing/_05a_run_ica Skipping …
[13:19:27] └╴🎉 preprocessing/_05a_run_ica Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_05b_run_ssp Now running  👇
[13:19:27] │ ⏩ preprocessing/_05b_run_ssp Skipping …
[13:19:27] └╴🎉 preprocessing/_05b_run_ssp Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_06a_apply_ica Now running  👇
[13:19:27] │ ⏩ preprocessing/_06a_apply_ica Skipping …
[13:19:27] └╴🎉 preprocessing/_06a_apply_ica Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_06b_apply_ssp Now running  👇
[13:19:27] │ ⏩ preprocessing/_06b_apply_ssp Skipping …
[13:19:27] └╴🎉 preprocessing/_06b_apply_ssp Done running  👆 [1s]
[13:19:27] ┌╴🚀 preprocessing/_07_ptp_reject Now running  👇
[13:19:27] │ ✅ preprocessing/_07_ptp_reject sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 preprocessing/_07_ptp_reject Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_01_make_evoked Now running  👇
[13:19:27] │ ✅ sensor/_01_make_evoked sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 sensor/_01_make_evoked Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_02_decoding_full_epochs Now running  👇
[13:19:27] │ ✅ sensor/_02_decoding_full_epochs sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 sensor/_02_decoding_full_epochs Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_03_decoding_time_by_time Now running  👇
[13:19:27] │ ✅ sensor/_03_decoding_time_by_time sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 sensor/_03_decoding_time_by_time Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_04_time_frequency Now running  👇
[13:19:27] │ ⏳️ sensor/_04_time_frequency Skipping …
[13:19:27] └╴🎉 sensor/_04_time_frequency Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_05_decoding_csp Now running  👇
[13:19:27] │ ⏩ sensor/_05_decoding_csp Skipping …
[13:19:27] └╴🎉 sensor/_05_decoding_csp Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_06_make_cov Now running  👇
[13:19:27] │ ✅ sensor/_06_make_cov sub-01 Computation unnecessary (cached) …
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:19:27] └╴🎉 sensor/_06_make_cov Done running  👆 [1s]
[13:19:27] ┌╴🚀 sensor/_99_group_average Now running  👇
[13:19:27] │ ⏳️ sensor/_99_group_average sub-average Input: sub-01_task-audiovisual_ave.fif
[13:19:38] │ ⏳️ sensor/_99_group_average sub-average Saving grand-averaged evoked sensor data: sub-average_task-audiovisual_ave.fif
[13:19:38] │ ⏳️ sensor/_99_group_average sub-average Generating grand average report …
[13:19:39] │ ⏳️ sensor/_99_group_average sub-average Adding 5 evoked signals and contrasts to the report.
[13:20:10] │ ⏳️ sensor/_99_group_average sub-average Adding decoding results.
[13:20:14] │ ⏳️ sensor/_99_group_average sub-average Adding config and sys info to report
[13:20:14] │ ⏳️ sensor/_99_group_average sub-average Saving report: /Users/richardhochenberger/mne_data/derivatives/mne-bids-pipeline/ds000248_no_mri/sub-average/meg/sub-average_task-audiovisual_report.html
/Users/richardhochenberger/Library/CloudStorage/OneDrive-FirmenichSA/Documents/Development/mne-bids-pipeline/mne_bids_pipeline/_run.py:317: FutureWarning: Setting the `book` attribute is not part of the public API, usage can give unexpected or corrupted results and will be removed in a future version
  writer.book = book
[13:20:14] └╴🎉 sensor/_99_group_average Done running  👆 [48s]
[13:20:14] ┌╴🚀 source/_01_make_bem_surfaces Now running  👇
[13:20:14] │ ⏩ source/_01_make_bem_surfaces Skipping, BEM surface extraction not needed for MRI template …
[13:20:14] └╴🎉 source/_01_make_bem_surfaces Done running  👆 [1s]
```

**Comment by larsoner** [comment]
... oh it's the group average that Rerun. I think that's a known thing that just hasn't been implemented yet

**Comment by larsoner** [comment]
Closing as dup of #609
