### ISSUE TITLE
AttributeError: 'OpenpyxlWriter' object has no attribute 'save'. Did you mean: '_save'?

### ISSUE THREAD

**Issue by LonghAb2020** [mne-tools/mne-bids-pipeline#739]
Hi, 

I am a new user to mne-bids-pipeline. I got the following errors while running the preprocessing pipeline. I use windows 10 + Anaconda Powershell. Any suggestion is greatly appreciated!

(base) PS C:\Users\zx22c> conda activate mne
(mne) PS C:\Users\zx22c> mne_bids_pipeline --config='C:/Users/zx22c/OneDrive - Florida State University/FSU/Lab/Projects/EmoAgeCI/HappySad/Results/custom_config.py' --steps=preprocessing
[16:35:40] ╶╴👋 Welcome aboard the MNE BIDS Pipeline!
[16:35:40] ╶╴🧾  Using configuration: C:/Users/zx22c/OneDrive - Florida State University/FSU/Lab/Projects/EmoAgeCI/HappySad/Results/custom_config.py
[16:35:40] ┌╴🚀 init/_01_init_derivatives_dir Now running  👇
[16:35:40] └╴🎉 init/_01_init_derivatives_dir Done running  👆 [0s]
[16:35:40] ┌╴🚀 init/_02_find_empty_room Now running  👇
[16:35:40] │ ⏩ init/_02_find_empty_room Skipping, empty-room data only relevant for MEG …
[16:35:40] └╴🎉 init/_02_find_empty_room Done running  👆 [1s]
[16:35:40] ┌╴🚀 preprocessing/_01_data_quality Now running  👇
Embedding : jquery-3.6.0.min.js
Embedding : bootstrap.bundle.min.js
Embedding : bootstrap.min.css
Embedding : bootstrap-table/bootstrap-table.min.js
Embedding : bootstrap-table/bootstrap-table.min.css
Embedding : bootstrap-table/bootstrap-table-copy-rows.min.js
Embedding : bootstrap-table/bootstrap-table-export.min.js
Embedding : bootstrap-table/tableExport.min.js
Embedding : bootstrap-icons/bootstrap-icons.mne.min.css
Embedding : highlightjs/highlight.min.js
Embedding : highlightjs/atom-one-dark-reasonable.min.css
[16:35:42] │ ⏳️ preprocessing/_01_data_quality sub-1001 Adding original raw data to report
[16:36:14] │ ⏳️ preprocessing/_01_data_quality sub-1001 Adding config and sys info to report
[16:36:14] │ ⏳️ preprocessing/_01_data_quality sub-1001 Saving report: C:\Users\zx22c\OneDrive - Florida State University\FSU\Lab\Projects\EmoAgeCI\HappySad\Results\derivatives\mne-bids-pipeline\sub-1001\eeg\sub-1001_task-emoageci_report.html
Overwriting existing file.
Saving report to : C:\Users\zx22c\OneDrive - Florida State University\FSU\Lab\Projects\EmoAgeCI\HappySad\Results\derivatives\mne-bids-pipeline\sub-1001\eeg\sub-1001_task-emoageci_report.h5
Overwriting existing file.
Saving report to : C:\Users\zx22c\OneDrive - Florida State University\FSU\Lab\Projects\EmoAgeCI\HappySad\Results\derivatives\mne-bids-pipeline\sub-1001\eeg\sub-1001_task-emoageci_report.html
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\mne\Scripts\mne_bids_pipeline-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\ProgramData\Anaconda3\envs\mne\Lib\site-packages\mne_bids_pipeline\_main.py", line 211, in main
    step_module.main(config=config_imported)
  File "C:\ProgramData\Anaconda3\envs\mne\Lib\site-packages\mne_bids_pipeline\steps\preprocessing\_01_data_quality.py", line 354, in main
    save_logs(config=config, logs=logs)
  File "C:\ProgramData\Anaconda3\envs\mne\Lib\site-packages\mne_bids_pipeline\_run.py", line 328, in save_logs
    writer.save()
    ^^^^^^^^^^^
AttributeError: 'OpenpyxlWriter' object has no attribute 'save'. Did you mean: '_save'?

**Comment by larsoner** [comment]
Can you try the latest version of mne-bids-pipeline? I think the bug has been fixed there

**Comment by LonghAb2020** [comment]
Thank you for feedback! This is my mne-bids-pipeline version: mne_bids_pipeline 1.2.0
I believe this is the last version. 
I still got the error: AttributeError: 'OpenpyxlWriter' object has no attribute 'save'. Did you mean: '_save'?_ 
Any suggestions?

**Comment by hoechenberger** [comment]
You are right, the fix is currently only in the development version and has not yet been released. 

@larsoner Would you mind cutting a 1.3 release? I think this fix alone warrants a new release.

**Comment by LonghAb2020** [comment]
Can you let me know when the new version is released? Thank you @hoechenberger and @larsoner!

**Comment by larsoner** [comment]
Done, should hit PyPI soon!

**Comment by LonghAb2020** [comment]
Thank you!
